name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  intl: ^0.17.0
  dio: ^5.4.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  line_icons: ^2.0.3
  lottie: ^2.7.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    # - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/sf-pro-display-cufonfonts/SFPRODISPLAYBOLD.OTF
          weight: 700
          style: normal
        - asset: fonts/sf-pro-display-cufonfonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
          style: normal
        - asset: fonts/sf-pro-display-cufonfonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
          style: normal


        
